# Colors
class COLORS:
    DARK_GREEN = '#005432'
    LIGHT_GREEN = '#006747'
    LIGHT_GOLD = '#CFC493'
    SAND = '#EDEBD1'
    LIGHT_GREY = '#EDF0F1'
    TEAL = '#009374'
    LEMON_GRASS = '#DBE442'
    APPLE = '#9CCB3B'
    STORM = '#006484'
    SLATE = '#466069'
    SEA_GLASS = '#80B0A6'


GENERAL_COLORS = [COLORS.DARK_GREEN, COLORS.LIGHT_GOLD, COLORS.SEA_GLASS]
OCCUPATION_COLORS = [COLORS.STORM, COLORS.APPLE]
CAMPUS_NAMES = ['Tampa', 'St. Petersburg', 'USF Health']
OCCUPATION_NAMES = ['Student', 'Employee']
PREDICTION_COL_NAMES = ['YHAT_TAMPA', 'YHAT_ST_PETE', 'YHAT_HEALTH']
